config/routes.rb
Project::Application.routes.draw do
  resources :fortunes

root :to => "fortunes#index"
match "/auth/:provider/callback" => "sessions#create"
match "/signout" => "sessions#destroy", :as => :signout
end

app/models/fortune.rb
class Fortune < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
def self.create_with_omniauth(auth)
  create! do |user|
    user.provider = auth["provider"]
    user.uid = auth["uid"]
    user.name = auth["user_info"]["name"]
  end
 end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

	helper_method :current_user

	private

	def current_user
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/fortunes_controller.rb
class FortunesController < ApplicationController
  # GET /fortunes
  # GET /fortunes.json
  def index
    @fortunes = Fortune.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fortunes }
    end
  end

  # GET /fortunes/1
  # GET /fortunes/1.json
  def show
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/new
  # GET /fortunes/new.json
  def new
    @fortune = Fortune.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fortune }
    end
  end

  # GET /fortunes/1/edit
  def edit
    @fortune = Fortune.find(params[:id])
  end

  # POST /fortunes
  # POST /fortunes.json
  def create
    @fortune = Fortune.new(params[:fortune])

    respond_to do |format|
      if @fortune.save
        format.html { redirect_to @fortune, notice: 'Fortune was successfully created.' }
        format.json { render json: @fortune, status: :created, location: @fortune }
      else
        format.html { render action: "new" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fortunes/1
  # PUT /fortunes/1.json
  def update
    @fortune = Fortune.find(params[:id])

    respond_to do |format|
      if @fortune.update_attributes(params[:fortune])
        format.html { redirect_to @fortune, notice: 'Fortune was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @fortune.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fortunes/1
  # DELETE /fortunes/1.json
  def destroy
    @fortune = Fortune.find(params[:id])
    @fortune.destroy

    respond_to do |format|
      format.html { redirect_to fortunes_url }
      format.json { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def create
	  auth = request.env["omniauth.auth"]
	  user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
	  session[:user_id] = user.id
	  redirect_to root_url, :notice => "Signed in!"
	end
	
	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Signed out!"
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fortunes_helper.rb
module FortunesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/fortunes/_form.html.erb
<%= simple_form_for(@fortune) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :quotation %>
    <%= f.input :source %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/fortunes/edit.html.erb
<h1>Editing fortune</h1>

<%= render 'form' %>

<%= link_to 'Show', @fortune %> |
<%= link_to 'Back', fortunes_path %>

app/views/fortunes/index.html.erb
<h1>Listing fortunes</h1>

<table>
  <tr>
    <th>Quotation</th>
    <th>Source</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fortunes.each do |fortune| %>
  <tr>
    <td><%= fortune.quotation %></td>
    <td><%= fortune.source %></td>
    <td><%= link_to 'Show', fortune %></td>
    <td><%= link_to 'Edit', edit_fortune_path(fortune) %></td>
    <td><%= link_to 'Destroy', fortune, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fortune', new_fortune_path %>

app/views/fortunes/new.html.erb
<h1>New fortune</h1>

<%= render 'form' %>

<%= link_to 'Back', fortunes_path %>

app/views/fortunes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Quotation:</b>
  <%= @fortune.quotation %>
</p>

<p>
  <b>Source:</b>
  <%= @fortune.source %>
</p>


<%= link_to 'Edit', edit_fortune_path(@fortune) %> |
<%= link_to 'Back', fortunes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Projekt</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

	<meta name="description" content="">
	<meta name="author" content="">

	<meta name="viewport" content="width=device-width,initial-scale=1">

  <%= stylesheet_link_tag    "style.css" %>
  <%= javascript_include_tag "modernizr-2.0.min.js" %>
  <%= javascript_include_tag "respond.min.js" %>
  <%= csrf_meta_tags %>	
<!--
<link rel="stylesheet" href="app/assets/stylesheet/style.css">

	<script src="app/assets/javascripts/libs/modernizr-2.0.min.js"></script>
	<script src="app/assets/javascripts/libs/respond.min.js"></script>
-->
</head>
<body>


<div id="header-container">
		<header class="wrapper">
			<h1 id="title">Fortunka</h1>			
			<nav>
				<ul>
					<li><a href="#">Some</a></li>
					<li><a href="#">navigation</a></li>
					<li><a href="#">links</a></li>
				</ul>
			</nav>
		</header>
	</div>
	<div id="main" class="wrapper">
	<div id="user_nav">
		<% if current_user %>
			 <%= current_user.name %> Witaj!
			<%= link_to "Wyloguj", signout_path %>
		<% else %>
			<%= link_to "Logowanie do twittera","/auth/twitter"%>
		<% end %>
	</div>		
		<aside>
			<h3>Dzień dobry państwu</h3>
		</aside>
		<article>
			<header>
				<h2><%= yield %></h2>
			</header>
			<h3>Złota myśl światowida</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sodales urna non odio egestas tempor. Nunc vel vehicula ante. Etiam bibendum iaculis libero, eget molestie nisl pharetra in. In semper consequat est, eu porta velit mollis nec. Curabitur posuere enim eget turpis feugiat tempor. Etiam ullamcorper lorem dapibus velit suscipit ultrices. Proin in est sed erat facilisis pharetra. Pellentesque auctor neque quis nisl lacinia id rutrum lacus venenatis.</p>	
			
			</footer>
		</article>
	</div>
	<div id="footer-container">
		<footer class="wrapper">
			<h3>Made in China</h3>
		</footer>
	</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
<script>window.jQuery || document.write('<%= javascript_include_tag "jquery-1.6.2.min.js" %>')</script>
<!--<script src="app/assets/javascripts/libs/jquery-1.6.2.min.js"><\script>-->
<%= javascript_include_tag "script.js" %>
<!--<script src="app/assets/javascripts/script.js"></script>-->
<script>

	var _gaq=[['_setAccount','UA-XXXXX-X'],['_trackPageview']]; // Change UA-XXXXX-X to be your site's ID
	(function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
	g.src=('https:'==location.protocol?'//ssl':'//www')+'.google-analytics.com/ga.js';
	s.parentNode.insertBefore(g,s)}(document,'script'));
</script>

<!--[if lt IE 7 ]>
	<script src="//ajax.googleapis.com/ajax/libs/chrome-frame/1.0.2/CFInstall.min.js"></script>
	<script>window.attachEvent("onload",function(){CFInstall.check({mode:"overlay"})})</script>
<![endif]-->

</body>
</html>